package me.listed.listedhack.client.hacks.chat;

import me.listed.listedhack.client.hacks.WurstplusCategory;
import me.listed.listedhack.client.hacks.WurstplusHack;
import me.listed.listedhack.client.util.WurstplusMessageUtil;

public class WurstplusBetterChat extends WurstplusHack {
   public WurstplusBetterChat() {
      super(WurstplusCategory.WURSTPLUS_CHAT);
      this.name = "Better Chat";
      this.tag = "BetterChat";
      this.description = "better chat :troll:";
   }

   public void enable() {
      super.enable();
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      WurstplusMessageUtil.send_client_message("POOP");
      this.set_disable();
   }
}
